products = [
  { name = "1/2 Hammer Drill", price = 299 },
  { name = "1/2 Impact Wrench", price = 299 },
  { name = "1/2 in Hole Hawg", price = 299 },
  { name = "1/4 Hex Impact", price = 149 },
  { name = "16Ga Finish Nailer", price = 329 },
  { name = "18Ga Brad Nailer", price = 399 },
  { name = "18Ga Crown Stapler", price = 299 },
  { name = "1in Impact", price = 799 },
  { name = "2 Gal Air Compressor", price = 349 },
  { name = "3/8 Compact Impact Wrench", price = 229 },
  { name = "3/8 Impact Wrench", price = 249 },
  { name = "6 Gal Shop Vac", price = 219 },
  { name = "6.0Ah Forge Battery", price = 199 },
  { name = "6.0Ah HO Battery", price = 279 },
  { name = "9 Gal Shop Vac", price = 299 },
  { name = "Bandsaw", price = 329 },
  { name = "Belt Sander", price = 279 },
  { name = "Bluetooth Speaker", price = 159 },
  { name = "Chainsaw", price = 499 },
  { name = "Circ", price = 249 },
  { name = "Compact Router", price = 199 },
  { name = "Cutoff Saw", price = 899 },
  { name = "DA Polisher", price = 329 },
  { name = "Grinder", price = 199 },
  { name = "Hackzall", price = 169 },
  { name = "Hedge Trimmer", price = 279 },
  { name = "Hole Hawg", price = 299 },
  { name = "Jig Saw", price = 199 },
  { name = "Leaf Blower", price = 399 },
  { name = "Mid Torque 1/2 Impact Wrench", price = 249 },
  { name = "Miter Saw", price = 449 },
  { name = "Packout LED Light", price = 199 },
  { name = "Packout Radio", price = 299 },
  { name = "Pole Saw", price = 349 },
  { name = "Rotary Hammer", price = 449 },
  { name = "Router", price = 349 },
  { name = "SDS Rotary Hammer", price = 499 },
  { name = "SDS-Plus Rotary Hammer", price = 349 },
  { name = "Sawzall", price = 199 },
  { name = "Shop Vac Set", price = 799 },
  { name = "Super Charger", price = 249 },
  { name = "Super Hawg", price = 429 },
  { name = "Super Hawg", price = 449 },
  { name = "Tower Light", price = 229 },
  { name = "Track Saw", price = 399 },
]
