db_path = "data.db"

[[promos]]
id = 320459258
name = "M18 Buy More Save More - Spring 2025"

[[promos]]
id = 315442497
name = "M12 Buy More Save More - Spring 2025"

[[promos]]
id = 326279262
name = "Landscaping Buy More Save More - Spring 2025"
